config/routes.rb
TheBuzziest::Application.routes.draw do

  match '/inbound_email/:city' => 'inbound_email#create'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  constraints :subdomain => "admin" do
    scope :module => "admin", :as => "admin" do
      get '', to: 'home#index', as: '/'
      resources :buzz_mentions, :only => [:index]
      resources :restaurants, :only => [:index]
    end
  end

  resources :buzz_mention_highlights
  resources :users
  resources :sessions
  resources :buzz_posts
  resources :buzz_sources
  resources :buzz_mentions do
    get 'toggle_ignore', :on => :member
  end
  resources :restaurants

  match '', to: 'restaurants#index', constraints: lambda { |r| r.subdomain.present? && ( r.subdomain == 'nyc' || r.subdomain == 'la' || r.subdomain == 'sf') }

  root :to => redirect(:subdomain => 'nyc')
    

end

app/views/admin/dashboard/_restaurants.erb
<table class="table table-striped">
  <thead>
    <tr>
    <th>Name</th>
    <th>City</th>
    <th>Twitter</th>
    <th class="buzz_mentions_score">Buzz Score</th>
    <th class="buzz_mentions_count">Buzz Mentions</th>
    <th>Opened On</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %>
        </td>
        <td><%= restaurant.city %>
        </td>
        <td><a target="_blank" href=http://www.twitter.com/<%= 
        restaurant.twitter_handle%>><%= restaurant.twitter_handle%>
        </td>
        <td class="buzz_mentions_score"><%= 
        number_with_precision(restaurant.total_current_buzz,:precision => 1) %>
        </td>
        <td class="buzz_mentions_count"><%=
        restaurant.buzz_mention_count_ignored %>
        </td>
        <td><%= restaurant.created_at.strftime("%b %d %y")  %>
        </td>
        <td>
          <% if can? :edit, @restaurant %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_restaurant_path(restaurant), :class => 'btn btn-mini' %>
            <%= link_to "Show", restaurant_path(restaurant),:class => 'btn btn-mini' %>
          <% end %>
          <% if can? :destroy, @restaurant %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), restaurant_path(restaurant), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, @restaurant %>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_restaurant_path, :class => 'btn btn-primary' %>
<% end %>

app/views/admin/dashboard/index_full.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <ul class="nav nav-list">
        <li>
          <a href="#">Dashboard</a>
        </li>
        <li class="active">
          <a href="#">Buzz Mentions</a>
        </li>
        <li>
          <a href="#">Buzz Posts</a>
        </li>
        <li>
          <a href="#">Restaurants</a>
        </li>
      </ul>
    </div>
    <div class="span10">
      <div class="row-fluid">
        <div class="list-content">
          <ul class="nav nav-tabs nav-append-content">
            <li class="active">
              <a href="#">New York</a>
            </li>
            <li>
              <a href="#">San Francisco</a>
            </li>
            <li>
              <a href="#">Los Angeles</a>
            </li>
            <li>
              <a href="#">All</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="New York">
              <table class="table table-striped table-hover table-bordered 
                table-condensed">
                <thead>
                  <tr>
                    <th>Restaurant</th>
                    <th>Blurb</th>
                    <th>Source</th>
                    <th>Created At</th>
                    <th>Ignore</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><span class="label label-primary">valid</span>
                    </td>
                    <td>1</td>
                    <td>The Shawshank Redemption</td>
                    <td>Crime, Drama</td>                                                                 <td>923,629</td>
                  </tr>
                  <tr>
                    <td><span class="label label-warning">ignored</span>
                    </td>
                    <td>1</td>
                    <td>The Shawshank Redemption</td>
                    <td>Crime, Drama</td>                                                                 <td>923,629</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="tab-pane" id="San Francisco">
            </div>
            <div class="tab-pane" id="Los Angeles">
            </div>
            <div class="tap-pane" id="All">
            </div>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>