config/routes.rb
TheBuzziest::Application.routes.draw do

  match '/inbound_email/:city' => 'inbound_email#create'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  constraints :subdomain => "admin" do
    scope :module => "admin", :as => "admin" do
      get '', to: 'home#index', as: '/'
      resources :buzz_mentions, :only => [:index]
      resources :restaurants, :only => [:index]
    end
  end

  resources :buzz_mention_highlights
  resources :users
  resources :sessions
  resources :buzz_posts
  resources :buzz_sources
  resources :buzz_mentions do
    get 'toggle_ignore', :on => :member
  end
  resources :restaurants

  match '', to: 'restaurants#index', constraints: lambda { |r| r.subdomain.present? && ( r.subdomain == 'nyc' || r.subdomain == 'la' || r.subdomain == 'sf') }

  root :to => redirect(:subdomain => 'nyc')
    

end

app/models/buzz_mention.rb
class BuzzMention < ActiveRecord::Base
  attr_accessible :buzz_post, :buzz_score, :restaurant_name, :restaurant_id,
                  :buzz_post_id, :decayed_buzz_score, :ignore, :highlight_text

  belongs_to :buzz_post
  belongs_to :restaurant

  has_many :buzz_sources, :through => :buzz_posts
  has_many :buzz_mention_highlights, :dependent => :destroy
  
  scope :not_ignored, where(:ignore => false)
  scope :ignored, where(:ignore => true)
  scope :tiny_decayed_buzz_score, where("decayed_buzz_score < ?", 0.05)  
  
  counter_culture :restaurant,
    :column_name => Proc.new {|model| (model.ignore == false) ?
      'buzz_mention_count_ignored' : nil }, :column_names => 
      { ["buzz_mentions.ignore = ?", false] => 'buzz_mention_count_ignored'}

  def update_decayed_buzz_score!
    born_on_date = self.buzz_post.post_date_time ||= self.created_at
    decay_factor = self.buzz_post.buzz_source.decay_factor.to_f ||= 0.906
    age_in_seconds = Time.now - born_on_date
    age_in_days = age_in_seconds/86400
    decayed_buzz_score = self.buzz_score*((decay_factor)**age_in_days)
    self.decayed_buzz_score = decayed_buzz_score
    self.save
  end

  def self.batch_create_from_search!(search_hits)
    progress_bar = ProgressBar.create(:format =>"%C %t %e %b", 
                                      :title => "mentions found...",
                                      :total => search_hits.count)
    search_hits.each do |hit|
      progress_bar.increment
      initial_buzz_score = BuzzPost.find(hit[:buzz_post_id]).post_weight
      unless self.exists?(:buzz_post_id => hit[:buzz_post_id],
                          :restaurant_id => hit[:restaurant_id])
        @buzz_mention = self.create(
          :restaurant_id => hit[:restaurant_id],
          :buzz_post_id => hit[:buzz_post_id], 
          :buzz_score => initial_buzz_score,
          :decayed_buzz_score => initial_buzz_score,
          :highlight_text => hit[:highlight]
        )
        @buzz_mention.update_decayed_buzz_score!
      end
    end
  end

  def self.destroy_old(buzz_mentions)
    progress_bar = ProgressBar.create(:format =>"%e %b", 
                                      :total => buzz_mentions.count)
    buzz_mentions.each do |buzz_mention|
      buzz_mention.destroy
      progress_bar.increment
    end
  end

  def self.older_than(age_in_days)
    where("created_at < :days", {:days => age_in_days.day.ago})
  end

  def self.ignored_and_older_than(age_in_days) 
    ignored_and_old = self.older_than(age_in_days).ignored
  end
end

app/controllers/admin/buzz_mentions_controller.rb
module Admin
  class BuzzMentionsController < AdminController
    
    def index
      @buzz_mentions = BuzzMention.find(:all, :order=>"id DESC") 
    end

  end
end

app/controllers/buzz_mentions_controller.rb
class BuzzMentionsController < ApplicationController

  load_and_authorize_resource

  def index
    @buzz_mentions = BuzzMention.paginate(:page => params[:page], :per_page => params[:per_page]).order(sort_column + ' ' + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @buzz_mentions }
    end
  end

  def show
    @buzz_mention = BuzzMention.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @buzz_mention = BuzzMention.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @buzz_mention = BuzzMention.find(params[:id])
  end

  def create
    @buzz_mention = BuzzMention.new(params[:buzz_mention])

    respond_to do |format|
      if @buzz_mention.save
        format.html { redirect_to @buzz_mention, notice: 'Buzz mention was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @buzz_mention = BuzzMention.find(params[:id])
    @buzz_mention.update_attributes!(params[:buzz_mention])
    respond_to do |format|
      format.html { redirect_to @buzz_mention, notice: 'Buzz mention was successfully updated.' }
      format.js
    end
  end


  def destroy
    @buzz_mention = BuzzMention.find(params[:id])
    @buzz_mention.destroy

    respond_to do |format|
      format.html { redirect_to buzz_mentions_url }
    end
  end

  def toggle_ignore
    @buzz_mention = BuzzMention.find(params[:id])
    @buzz_mention.toggle!(:ignore)

    respond_to do |format|
      format.js
    end
  end

  def per_page
   params[:per_page] ||= 50
  end

private
  def sort_column
    BuzzMention.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/buzz_mentions_helper.rb
module BuzzMentionsHelper
end

app/views/buzz_mentions/_buzz_mentions.erb
<%= link_to buzz_mention.buzz_post.post_title,
  buzz_mention.buzz_post.post_uri,
  "id"=> "buzz_mention_#{buzz_mention.id}",
  "class" => "ignore_#{buzz_mention.ignore}",
  "target" => "_blank" %>

app/views/buzz_mentions/_buzz_mentions_with_highlights.erb
<%= link_to(buzz_mention.buzz_post.post_title, 
            buzz_mention.buzz_post.post_uri, 
            "class" => "mention_highlight ignore_#{buzz_mention.ignore}",
            "id" => "buzz_mention_#{buzz_mention.id}",
            "target" => "_blank",
            "data-content" => buzz_mention.buzz_mention_highlights.first.buzz_mention_highlight_text ,
            "data-toggle" =>"popover", "data-placement"=>"top", "data-trigger" => "hover") %>

app/views/buzz_mentions/_form.html.erb
<%= form_for(@buzz_mention) do |f| %>
  <% if @buzz_mention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buzz_mention.errors.count, "error") %> prohibited this buzz_post from being saved:</h2>

      <ul>
      <% @buzz_mention.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buzz_post_id %><br />
    <%= f.text_field :buzz_post_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.text_field  :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :decayed_buzz_score %><br />
    <%= f.text_field :decayed_buzz_score %>
  </div>
  <div class="field">
    <%= f.label :buzz_score %><br />
    <%= f.text_field  :buzz_score %>
  </div>
  <div class="field">
    <%= f.label :ignore %><br />
    <%= f.check_box :ignore %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buzz_mentions/edit.html.erb
<h1>Editing buzz_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @buzz_post %> |
<%= link_to 'Back', buzz_posts_path %>

app/views/buzz_mentions/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Buzz Mention ID</th>
      <th>Restaurant Name</th>
      <th>Buzz Post Title</th>
      <th>Ignore?</th>
      <th>Buzz Post Source</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @buzz_mentions.each do |buzz_mention| %>
      <tr>
        <td><%= buzz_mention.id%></td>
        <td><%= buzz_mention.restaurant.name %></td>

        <% if buzz_mention.buzz_mention_highlights.exists? %>
          <td><%= render :partial => 'buzz_mentions/buzz_mentions_with_highlights',
            :locals => {:buzz_mention => buzz_mention} %>
          </td>
        <% else %>
          <td> <%= render :partial => 'buzz_mentions/buzz_mentions', 
            :locals => {:buzz_mention => buzz_mention} %>
          </td>
        <% end %>
        <td><% if can? :edit, @buzz_mention %>
          <%= link_to ignore_link_text(buzz_mention),
            toggle_ignore_buzz_mention_path(buzz_mention),
            :remote => true, :id => "ignore_link_#{buzz_mention.id}" %>
          <% end %>
        </td>
        <td><%= buzz_mention.buzz_post.buzz_source.name %></td>
        <td><%= buzz_mention.created_at %></td>
        <td>
          <%= link_to 'Show', buzz_mention %>
          <% if can? :edit, buzz_mention %>
            <%= link_to 'Edit', edit_buzz_mention_path(buzz_mention) %>
          <% end %>
          <%= link_to 'Destroy', buzz_mention,
            confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @buzz_mentions, :page_links => false %>

<br />

app/views/buzz_mentions/new.html.erb
<h1>New buzz_post</h1>

<%= render 'form' %>

<%= link_to 'Back', buzz_posts_path %>

app/views/buzz_mentions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Buzz mention id:</b>
  <%= @buzz_mention.id %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @buzz_mention.restaurant.name %>
</p>

<p>
  <b>Buzz Post Title:</b>
  <%= @buzz_mention.buzz_post.post_title %>
</p>

<p>
  <b>Buzz Post Source:</b>
  <%= @buzz_mention.buzz_post.buzz_source.name %>
</p>

<p>
  <b>Buzz Post Content:</b>
  <%= @buzz_mention.buzz_post.post_content %>
</p>

<p>
  <b>Created At:</b>
  <%= @buzz_mention.created_at %>
</p>


<%= link_to 'Back', buzz_mentions_path %>