config/routes.rb
TheBuzziest::Application.routes.draw do

  match '/inbound_email/:city' => 'inbound_email#create'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  constraints :subdomain => "admin" do
    scope :module => "admin", :as => "admin" do
      get '', to: 'home#index', as: '/'
      resources :buzz_mentions, :only => [:index]
      resources :restaurants, :only => [:index]
    end
  end

  resources :buzz_mention_highlights
  resources :users
  resources :sessions
  resources :buzz_posts
  resources :buzz_sources
  resources :buzz_mentions do
    get 'toggle_ignore', :on => :member
  end
  resources :restaurants

  match '', to: 'restaurants#index', constraints: lambda { |r| r.subdomain.present? && ( r.subdomain == 'nyc' || r.subdomain == 'la' || r.subdomain == 'sf') }

  root :to => redirect(:subdomain => 'nyc')
    

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :description, :name, :neighborhood, :twitter_handle, :reserve, 
                  :style, :skip_scan, :exact_match, :total_current_buzz, :city, 
                  :filter_words

  has_many :buzz_mentions, :dependent => :destroy
  has_many :buzz_posts, :through => :buzz_mentions
  has_many :buzz_scores, :dependent => :destroy

  validates :name, :uniqueness => true

  scope :with_buzz, where("buzz_mention_count_ignored > 0")
  scope :not_skipped, where(:skip_scan => false)
  
  searchable do
    text :name
  end
 
  def fetch_and_update_twitter_handle!
    twitter_client = Fetch::TwitterHandle::Client.new(self.name)
    twitter_client.fetch_and_parse
    self.twitter_handle = twitter_client.twitter_handle 
    self.save
  end

  def total_score 
    total_score = self.buzz_mentions.not_ignored.sum("decayed_buzz_score")    
  end

  
  def self.batch_create_from_remote(remote_source_client)
    names = remote_source_client.name_list
    names.each do |name|
      restaurant = Restaurant.where(:name => 
        name[:name]).first_or_create(:city => name[:city]) 
      if restaurant.twitter_handle == nil
        restaurant.fetch_and_update_twitter_handle!
      end
    end
  end

  private

  def self.fuzzy_match(name)
    fuzzy_match = self.search do
      fulltext %Q/"#{name}"/
    end
    fuzzy_match = fuzzy_match.results
  end
end

app/controllers/admin/restaurants_controller.rb
module Admin
  class RestaurantsController < AdminController
    
    def index
      @restaurants = Restaurant.find(:all, :order=>"total_current_buzz DESC")
    end

    def show
      @restaurant = Restaurant.find params[:id]
    end

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  helper_method :sort_column, :sort_direction

  load_and_authorize_resource

  def index
    @restaurants = Restaurant.where("city = ? AND buzz_mention_count_ignored > ? AND total_current_buzz > ?",request.subdomain, 0, 0.4).order("total_current_buzz DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

private
  def sort_column
    Restaurant.column_names.include?(params[:sort]) ? params[:sort] : "total_current_buzz"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end


end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def latest_buzz(restaurant)
    buzz = BuzzScore.where(:restaurant_id => restaurant.id).last(:order => "id asc", :limit => 1)
    if buzz == nil
      latest_buzz_score = 0
    else
      latest_buzz_score = buzz.buzz_score
    end
    return latest_buzz_score
  end

end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :style, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :style, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :neighborhood, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :neighborhood, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reserve, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reserve, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :twitter_handle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter_handle, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :exact_match, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :exact_match, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :skip_scan, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :skip_scan, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), restaurants_path, :class => 'btn' %>
  </div>
<% end %>

app/views/restaurants/_restaurants.html.erb
<table class="table table-striped">
  <thead>
    <tr>
    <th>Name</th>
    <th>Twitter</th>
    <th class="buzz_mentions_score">Buzz Score</th>
    <th class="buzz_mentions_count">Buzz Mentions</th>
    <th>Opened On</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><a target="_blank" href=http://www.twitter.com/
            <%= restaurant.twitter_handle%>><%= restaurant.twitter_handle%></a>
        </td>
        <td class="buzz_mentions_score">
          <%= number_with_precision(restaurant.
                                    total_current_buzz,:precision => 1) %></td>
        <td class="buzz_mentions_count"><%= restaurant.
                                            buzz_mention_count_ignored %></td>
        <td><%= restaurant.created_at.strftime("%b %d %y")  %></td>
        <td>
          <% if can? :edit, @restaurant %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_restaurant_path(restaurant), :class => 'btn btn-mini' %>
            <%= link_to "Show", restaurant_path(restaurant),
                :class => 'btn btn-mini' %>
          <% end %>
          <% if can? :destroy, @restaurant %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              restaurant_path(restaurant), :method => :delete, 
              :confirm => t('.confirm',
                            :default => t("helpers.links.confirm",
                                          :default => 'Are you sure?')),
                            :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, @restaurant %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
    new_restaurant_path, :class => 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<%- model_class = @restaurant.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/restaurants/index.js.erb
$('#restaurants').html('<%= escape_javascript(render :partial => "restaurants" %>');

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong><br>
  <%= @restaurant.name %>
</p>
<!-- <p>
  <strong>Style:</strong><br>
  </%= @restaurant.style %>
</p>
<p>
  <strong>Weeks on List:</strong><br>
  </%= @restaurant.weeks_on_list %>
</p>
<p>
  <strong>Neighborhood</strong><br>
  </%= @restaurant.neighborhood %>
</p>
<p>
  <strong>Reserve:</strong><br>
  </%= @restaurant.reserve %>
</p> -->
<!-- <p>
  <strong>Description</strong><br>
  </%= @restaurant.description %>
</p> -->
<!-- <p>
  <strong>Twitter</strong><br>
  </%= @restaurant.twitter_handle %>
</p>
<p>
  <strong>Exact Match Only?</strong><br>
  </%= @restaurant.exact_match %>
</p>
<p>
  <strong>Make Inactive (hide)?:</strong><br>
  </%= @restaurant.skip_scan %>
</p> -->
<p>
  <strong>City</strong><br>
  <%= @restaurant.city %>
</p>
<p>
  <strong>Total Current Buzz</strong><br>
  <%= @restaurant.total_current_buzz %>
</p>

  <b>Buzz Mentions:</b><br/>
    <% @restaurant.buzz_mentions.each do |buzz_mention| %>
    <div id="buzz_mention_<%=buzz_mention.id%>">
    <% if can? :edit, @buzz_mention %>
      <%= link_to ignore_link_text(buzz_mention),toggle_ignore_buzz_mention_path(buzz_mention),:remote => true, :id => "ignore_link_#{buzz_mention.id}" %> - 
    <% end %>
    <% if buzz_mention.buzz_mention_highlights.exists? %>
      <%= render :partial => 'buzz_mentions/buzz_mentions_with_highlights', :locals => {:buzz_mention => buzz_mention} %>
    <% else %>
      <%= render :partial => 'buzz_mentions/buzz_mentions', :locals => {:buzz_mention => buzz_mention} %>
    <% end %>
     - <%=buzz_mention.buzz_post.post_date_time%>
    <br/>
    </div>
  <% end %>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              restaurants_path, :class => 'btn'  %>
  <% if can? :edit, @restaurant %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),edit_restaurant_path(@restaurant), :class => 'btn' %>
  <% end %>
</div>