config/routes.rb
TheBuzziest::Application.routes.draw do

  match '/inbound_email/:city' => 'inbound_email#create'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  constraints :subdomain => "admin" do
    scope :module => "admin", :as => "admin" do
      get '', to: 'home#index', as: '/'
      resources :buzz_mentions, :only => [:index]
      resources :restaurants, :only => [:index]
    end
  end

  resources :buzz_mention_highlights
  resources :users
  resources :sessions
  resources :buzz_posts
  resources :buzz_sources
  resources :buzz_mentions do
    get 'toggle_ignore', :on => :member
  end
  resources :restaurants

  match '', to: 'restaurants#index', constraints: lambda { |r| r.subdomain.present? && ( r.subdomain == 'nyc' || r.subdomain == 'la' || r.subdomain == 'sf') }

  root :to => redirect(:subdomain => 'nyc')
    

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield_or_default(:title, "") %>The Buzziest</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= bootstrap_flash %>

</head>
<body>

  <div class="navbar navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">The Buzziest | NYC</a>
        <div class="nav-collapse">
        <div id="user_header">
          <% if current_user %>
            Hello <%= current_user.email %>.
            <%= link_to "Log Out", logout_path %>
          <% else %>
            <%= link_to "Sign Up", signup_path %> or
            <%= link_to "Log In", login_path %>
          <% end %>
        </div>
          <ul class="nav">
            <!-- <li></%= link_to "Restaurants", restaurants_path %></li>
            <li></%= link_to "Buzz Posts", buzz_posts_path %></li> -->
          </ul>
        </div>
      </div>
    </div>
  </div>

<div class="container main-body">
  <%= yield %>
</div>
</body>
</html>